import random

word_list={
'a, an': 'bir',
'abandon ': 'terketmek',
'ability ': 'yetenek',
'able ': 'gücü yeten, hünerli',
'about ': 'yaklaşık',
'above ': 'üstünde',
'abroad ': 'yurt dışı',
'absolute ': 'tam, mutlak',
'absolutely ': 'kesinlikle',
'academic ': 'akademik',
'accept ': 'kabul etmek',
'acceptable ': 'kabul edilir',
'access ': 'erişim',
'accident ': 'kaza, rastlantı',
'accommodation ': 'kalacak yer',
'accompany ': 'eşlik etmek',
'according to ': 'e göre',
'account ': 'hesap',
'accurate ': 'doğru, kesin',
'accuse ': 'suçlamak',
'achieve ': 'başarmak',
'achievement ': 'başarı',
'acknowledge ': 'kabullenmek',
'acquire ': 'elde etmek',
'across ': 'karşı',
'act ': 'eylem, yasa, davranmak',
'action ': 'çalışma, davranış',
'active ': 'aktif',
'activity ': 'etkinlik',
'actor ': 'erkek oyuncu',
'actress ': 'kadın oyuncu',
'actual ': 'gerçek, fiili',
'actually ': 'aslında, fiilen',
'ad ': 'reklam, ilan',
'adapt ': 'uyarlamak, uymak',
'add ': 'eklemek, toplamak',
'addition ': 'ilave',
'additional ': 'fazladan',
'address ': 'adres',
'administration ': 'yönetim',
'admire ': 'hayranlık duymak',
'admit ': 'itiraf etmek, kabul etmek',
'adopt ': 'evlat edinmek, benimsemek',
'adult ': 'yetişkin',
'advance ': 'terfi, avans',
'advanced ': 'modern, gelişmiş',
'advantage ': 'avantaj, fayda',
'adventure ': 'macera, serüven',
'advertise ': 'reklamını yapmak',
'advertisement ': 'reklam',
'advertising ': 'reklamcılık',
'advice ': 'nasihat, tavsiye',
'advise ': 'öğütlemek',
'affair ': 'mesele',
'affect ': 'etkilemek, tesir etmek',
'afford ': 'parası yetmek',
'afraid ': 'korkmuş',
'after ': 'sonra',
'afternoon ': 'öğleden sonra',
'afterwards ': 'sonradan',
'again ': 'bir daha, tekrar',
'against ': 'aykırı, karşı',
'age ': 'yaş, çağ',
'aged ': 'yaşlı, yıllanmış',
'agency ': 'ajans',
'agenda ': 'gündem, ajanda',
'agent ': 'temsilci',
'aggressive ': 'agresif',
'ago ': 'önce',
'agree ': 'hemfikir olmak',
'agreement ': 'anlaşma',
'ah ': 'of, ya, vah',
'ahead ': 'ilerisi',
'aid ': 'yardım etmek',
'aim ': 'amaç, hedef',
'air ': 'hava, havalandırmak',
'aircraft ': 'uçak',
'airline ': 'hava yolu',
'airport ': 'havalimanı',
'alarm ': 'alarm',
'album ': 'albüm, plak,..',
'alcohol ': 'alkol',
'alcoholic ': 'alkolik, alkollü',
'alive ': 'canlı, diri',
'all ': 'hepsi',
'all right ': 'elbette',
'allow ': 'izin vermek',
'almost ': 'neredeyse',
'alone ': 'yalnız',
'along ': 'boyunca',
'already ': 'halihazırda',
'also ': 'ayrıca',
'alter ': 'değiştirmek',
'alternative ': 'alternatif',
'although ': 'rağmen',
'always ': 'daima',
'amazed ': 'şaşırmış',
'amazing ': 'şaşırtıcı, harika',
'ambition ': 'hırs',
'ambitious ': 'hırslı',
'among ': 'arasına',
'amount ': 'miktar, tutar',
'analyse ': 'incelemek',
'analysis ': 'çözümleme',
'ancient ': 'antik',
'and ': 'ile, ve',
'anger ': 'sinir, öfke',
'angle ': 'açı',
'angry ': 'sinirli',
'animal ': 'hayvan',
'ankle ': 'ayak bileği',
'anniversary ': 'yıl dönümü',
'announce ': 'duyurmak, ilan etmek',
'announcement ': 'duyuru, ilan',
'annoy ': 'rahatsız etmek, sinirlendirmek',
'annoyed ': 'sinirli, kızgın',
'annoying ': 'gıcık, rahatsız edici',
'annual ': 'yıllık',
'another ': 'diğer',
'answer ': 'cevap',
'anxious ': 'huzursuz, kaygılı',
'any ': 'hiçbir, herhangi',
'anybody ': 'herhangi biri, hiç kimse',
'any more ': 'daha fazla',
'anyone ': 'hiç kimse, herhangi birisi',
'anything ': 'hiçbir şey, her şey',
'anyway ': 'her neyse',
'anywhere ': 'herhangi bir yer',
'apart ': 'ayrı',
'apartment ': 'daire',
'apologize ': 'özür dilemek',
'app ': 'uygulama',
'apparent ': 'aşikar, belirgin',
'apparently ': 'anlaşılan, görünüşte',
'appeal ': 'başvuru',
'appear ': 'görünmek, belli olmak',
'appearance ': 'görünüş',
'apple ': 'elma',
'application ': 'uygulama, müracat',
'apply ': 'uygulamak, müracat etmek',
'appointment ': 'tayin, randevu',
'appreciate ': 'değerini artırmak, takdir etmek',
'approach ': 'yaklaşım, yanaşmak',
'appropriate ': 'uygun, el koymak',
'approval ': 'onaylama',
'approve ': 'onaylamak',
'approximately ': 'yaklaşık olarak',
'April ': 'nisan',
'architect ': 'mimar',
'architecture ': 'mimarlık',
'area ': 'alan, saha',
'argue ': 'tartışmak',
'argument ': 'argüman, tartışma',
'arise ': 'baş göstermek, meydnaa çıkmak',
'arm ': 'kol',
'armed ': 'zırhlı, silahlandırılmış',
'arms ': 'silah, cephane',
'army ': 'ordu',
'around ': 'etrafında',
'arrange ': 'ayarlamak, düzenlemek',
'arrangement ': 'ayarlama, düzenleme',
'arrest ': 'tutuklamak',
'arrival ': 'varma, gelme',
'arrive ': 'varmak, ulaşmak',
'art ': 'sanat',
'article ': 'makale, madde',
'artificial ': 'yapay, suni',
'artist ': 'sanatçı, ressam',
'artistic ': 'sanatsal',
'as ': 'olarak, gibi',
'ashamed ': 'mahcup, utanmış',
'ask ': 'soru sormak, istemek',
'asleep ': 'uyuyan, tembel',
'aspect ': 'yön, taraf',
'assess ': 'değer biçmek',
'assessment ': 'değerlendirme',
'assignment ': 'görevlendirme, ödev, görev',
'assist ': 'yardım etmek',
'assistant ': 'yardımcı',
'associate ': 'birleştirmek, iş arkadaşı',
'associated ': 'bağlantılı, birleşmiş',
'association ': 'birlik, dernek',
'assume ': 'üstlenmek, farz etmek',
'at ': 'üzere',
'athlete ': 'sporcu',
'atmosphere ': 'atmosfer',
'attach ': 'yapıştırmak, iliştirmek',
'attack ': 'saldırı',
'attempt ': 'kalkışma, girişim',
'attend ': 'katılmak',
'attention ': 'ilgilenme, özen',
'attitude ': 'tutum, tavır',
'attract ': 'cezbetmek',
'attraction ': 'cazibe',
'attractive ': 'çekici',
'audience ': 'seyirci, izleyici',
'August ': 'ağustos',
'aunt ': 'hala, teyze',
'author ': 'yazar, yaratıcı',
'authority ': 'yetki',
'autumn ': 'sonbahar',
'available ': 'mevcut, müsait',
'average ': 'ortalama',
'avoid ': 'kaçınmak',
'award ': 'ödül',
'aware ': 'farkında, haberdar',
'away ': 'uzak',
'awful ': 'berbat',
'baby ': 'bebek',
'back ': 'arka, sırt',
'background ': 'arka plan, fon',
'backwards ': 'geriye',
'bacteria ': 'bakteri',
'bad ': 'kötü',
'badly ': 'kötü bir şekilde',
'bag ': 'torba, çanta',
'bake ': 'fırında pişirmek',
'balance ': 'bakiye, denge',
'ball ': 'bilye, top, yumak',
'ban ': 'yasaklamak',
'banana ': 'muz',
'band ': 'bant, bando',
'bank (money) ': 'banka',
'bank (river) ': 'nehir kıyısı',
'bar ': 'çubuk, parmaklık',
'barrier ': 'set, bariyer',
'base ': 'temel, taban',
'baseball ': 'beyzbol',
'based ': 'esaslı, merkezli',
'basic ': 'temel, esas, ana',
'basically ': 'aslen',
'basis ': 'temel',
'basketball ': 'basketbol',
'bath ': 'banyo, yıkanmak',
'bathroom ': 'tuvalet',
'battery ': 'akü, pil',
'battle ': 'savaş',
'be ': 'olmak, bulunmak',
'beach ': 'sahil',
'bean ': 'fasulye',
'bear (deal with) ': 'dayanmak',
'bear (animal) ': 'ayı',
'beat ': 'darbe, vurmak, çarpma',
'beautiful ': 'güzel',
'beauty ': 'güzellik',
'because ': 'çünkü',
'become ': 'olmak, dönüşmek',
'bed ': 'yatak',
'bedroom ': 'yatak odası',
'bee ': 'arı',
'beef ': 'biftek',
'beer ': 'bira'
}
kelime=list(word_list.keys())
print ('Ingilizce Kelime Tekrarı. 10 round. Oyundan çıkmak için q yaz.')
point=0
for i in range(10):
    kelimesec=random.choice(kelime)
    turkce = word_list[kelimesec]
    user_guess = input('Kelime: %s '%kelimesec )
    if user_guess.lower() == 'q':
        break
    elif user_guess == turkce:
        point+=1
        print('Doğru! Yeni skorun: %d' %point)
    else:
        print('Yanlış. {} kelimesinin anlamı: {}.'.format(kelimesec,turkce))
input('Oyun bitti. Skorun: %d.' %point)